name: Run Python Script

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Run script
      run: python https://github.com/Reinaldo-Jr-Dev/doutorado/blob/master/smote/smote-v1.py  # substitua pelo caminho do seu script
