name: Python application - Técnicas

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # ou a versão que você preferir

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install imbalanced-learn
        pip install numpy

    - name: Run script
      run: |
        python smote/smote-v1.py
