name: Python application

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # ou a versão que você preferir

    - name: Run script
      run: |
        python /home/runner/work/doutorado/doutorado/smote/smote-v1.py  # Substitua pelo nome do seu arquivo Python
